services:
  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: tarefa
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - gerenciador-de-estoque-db:/var/lib/mysql

volumes:
  gerenciador-de-estoque-db: